version: '3'

services:

  postgres:
    image: "postgres:12"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: squad
      POSTGRES_PASSWORD: squad123
      POSTGRES_DB: desafio-squad

volumes:
  db_data: